# Generated by Django 4.0.5 on 2022-06-18 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstudiosLaboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(blank=True, max_length=100)),
                ('nombre', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PacienteInformacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_nacimiento', models.CharField(blank=True, max_length=100, null=True)),
                ('sexo', models.CharField(default='M', max_length=10)),
                ('lugar_nacimiento', models.CharField(blank=True, max_length=100, null=True)),
                ('ficha', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PruebaLaboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.IntegerField(default=0)),
                ('prueba', models.CharField(blank=True, max_length=100)),
                ('estudio', models.CharField(blank=True, max_length=100)),
                ('resultado', models.CharField(max_length=100)),
                ('unidad', models.CharField(max_length=100)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_table.pacienteinformacion')),
            ],
        ),
    ]
