# Generated by Django 4.0.5 on 2022-06-28 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_table', '0004_pruebalaboratorio_nombre_paciente'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacienteinformacion',
            name='aumento_colesterol_HDL',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pacienteinformacion',
            name='aumento_trigliceridos',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pacienteinformacion',
            name='edad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pacienteinformacion',
            name='glicemia_ayunas',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pacienteinformacion',
            name='indice_de_masa_corporal',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pacienteinformacion',
            name='medicacion_anti_hipertensiva',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pacienteinformacion',
            name='medicion_cintura',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pacienteinformacion',
            name='tension_arterial',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
