# Generated by Django 4.0.5 on 2022-06-30 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_table', '0006_qs30'),
    ]

    operations = [
        migrations.AddField(
            model_name='qs30',
            name='glucosa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='qs30',
            name='nitrOgeno_Ureico',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='qs30',
            name='urea_serica',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
