# Generated by Django 4.0.5 on 2022-07-05 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_table', '0007_qs30_glucosa_qs30_nitrogeno_ureico_qs30_urea_serica'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacienteinformacion',
            name='clasificacion_de_obesidad',
            field=models.CharField(blank=True, choices=[('Bajo Peso', 'Bajo Peso'), ('Peso Ideal', 'Peso Ideal'), ('Sobrepeso', 'Sobrepeso'), ('Obesidad', 'Obesidad'), ('Obesidad Severa', 'Obesidad Severa'), ('Obesidad Mórbida', 'Obesidad Mórbida')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pacienteinformacion',
            name='peso',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pacienteinformacion',
            name='talla',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
