# Generated by Django 4.0.5 on 2022-07-11 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_table', '0008_pacienteinformacion_clasificacion_de_obesidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacienteinformacion',
            name='antecedentes_diabetes',
            field=models.CharField(blank=True, default='No', max_length=100, null=True),
        ),
    ]
