# Generated by Django 4.0.5 on 2022-07-11 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_table', '0009_pacienteinformacion_antecedentes_diabetes'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacienteinformacion',
            name='consentimiento_informado',
            field=models.CharField(blank=True, default='No', max_length=100, null=True),
        ),
    ]
