# Generated by Django 4.0.5 on 2022-07-15 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_table', '0010_pacienteinformacion_consentimiento_informado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacienteinformacion',
            name='curp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
